//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraftFlow.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CraftFlow.Wpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receive Lot.
        /// </summary>
        public static string ADD_STOCK_LOT {
            get {
                return ResourceManager.GetString("ADD_STOCK_LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chamber Name.
        /// </summary>
        public static string AGING_CHAMBER_NAME {
            get {
                return ResourceManager.GetString("AGING_CHAMBER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на — All Suppliers —.
        /// </summary>
        public static string ALL_SUPPLIERS {
            get {
                return ResourceManager.GetString("ALL_SUPPLIERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на — All Warehouses —.
        /// </summary>
        public static string ALL_WAREHOUSES {
            get {
                return ResourceManager.GetString("ALL_WAREHOUSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batch Number:.
        /// </summary>
        public static string BATCH_NUMBER {
            get {
                return ResourceManager.GetString("BATCH_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string BTN_ADD {
            get {
                return ResourceManager.GetString("BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Equipment.
        /// </summary>
        public static string BTN_CREATE_EQUIPMENT {
            get {
                return ResourceManager.GetString("BTN_CREATE_EQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log Out.
        /// </summary>
        public static string BTN_LOGOUT {
            get {
                return ResourceManager.GetString("BTN_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Container.
        /// </summary>
        public static string BTN_QUICK_NEW_LOCATION {
            get {
                return ResourceManager.GetString("BTN_QUICK_NEW_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string BTN_REFRESH {
            get {
                return ResourceManager.GetString("BTN_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write Off.
        /// </summary>
        public static string BTN_WRITE_OFF {
            get {
                return ResourceManager.GetString("BTN_WRITE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ Insufficient capacity! Required: {0:N0} l/kg, available: {1:N0} l/kg.
        /// </summary>
        public static string CAPACITY_WARNING_INSUFFICIENT {
            get {
                return ResourceManager.GetString("CAPACITY_WARNING_INSUFFICIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Capacity is sufficient (selected {0:N0} l/kg for batch of {1:N0} l/kg).
        /// </summary>
        public static string CAPACITY_WARNING_SUFFICIENT {
            get {
                return ResourceManager.GetString("CAPACITY_WARNING_SUFFICIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expiring Soon Only.
        /// </summary>
        public static string CHECK_EXPIRING_SOON {
            get {
                return ResourceManager.GetString("CHECK_EXPIRING_SOON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action.
        /// </summary>
        public static string COL_ACTION {
            get {
                return ResourceManager.GetString("COL_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created At (UTC).
        /// </summary>
        public static string COL_CREATED_AT {
            get {
                return ResourceManager.GetString("COL_CREATED_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string COL_DETAILS {
            get {
                return ResourceManager.GetString("COL_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entity Name.
        /// </summary>
        public static string COL_ENTITY_NAME {
            get {
                return ResourceManager.GetString("COL_ENTITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Material.
        /// </summary>
        public static string CREATE_RAW_MATERIAL {
            get {
                return ResourceManager.GetString("CREATE_RAW_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Recipe.
        /// </summary>
        public static string CREATE_RECIPE {
            get {
                return ResourceManager.GetString("CREATE_RECIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Supplier.
        /// </summary>
        public static string CREATE_SUPPLIER {
            get {
                return ResourceManager.GetString("CREATE_SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid email format.
        /// </summary>
        public static string GENERAL_INVALID_EMAIL_FORMAT {
            get {
                return ResourceManager.GetString("GENERAL.INVALID_EMAIL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid organization identifier (Tenant).
        /// </summary>
        public static string GENERAL_INVALID_TENANT {
            get {
                return ResourceManager.GetString("GENERAL_INVALID_TENANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requested resource not found.
        /// </summary>
        public static string GENERAL_NOT_FOUND {
            get {
                return ResourceManager.GetString("GENERAL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Required field not filled in.
        /// </summary>
        public static string GENERAL_VALUE_REQUIRED {
            get {
                return ResourceManager.GetString("GENERAL_VALUE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Stock Balances in Warehouses.
        /// </summary>
        public static string GROUP_CURRENT_STOCK {
            get {
                return ResourceManager.GetString("GROUP_CURRENT_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receive Stock Lot into Warehouse.
        /// </summary>
        public static string GROUP_RECEIVE_STOCK_LOT {
            get {
                return ResourceManager.GetString("GROUP_RECEIVE_STOCK_LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Raw Material Lot for Write-off (flushing, boil-off, defect, loss).
        /// </summary>
        public static string GROUP_WRITE_OFF_SELECTION {
            get {
                return ResourceManager.GetString("GROUP_WRITE_OFF_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Guest (not logged in).
        /// </summary>
        public static string GUEST_USER {
            get {
                return ResourceManager.GetString("GUEST_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aging Chambers.
        /// </summary>
        public static string HEADER_AGING_CHAMBERS {
            get {
                return ResourceManager.GetString("HEADER_AGING_CHAMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Containers, Tanks &amp; Racks.
        /// </summary>
        public static string HEADER_EQUIPMENT {
            get {
                return ResourceManager.GetString("HEADER_EQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Recipe.
        /// </summary>
        public static string HEADER_NEW_RECIPE {
            get {
                return ResourceManager.GetString("HEADER_NEW_RECIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raw Materials &amp; Ingredients.
        /// </summary>
        public static string HEADER_RAW_MATERIALS {
            get {
                return ResourceManager.GetString("HEADER_RAW_MATERIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Technology Recipes.
        /// </summary>
        public static string HEADER_RECIPES {
            get {
                return ResourceManager.GetString("HEADER_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Supplier.
        /// </summary>
        public static string HEADER_SUPPLIERS {
            get {
                return ResourceManager.GetString("HEADER_SUPPLIERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RECIPE FORMULA.
        /// </summary>
        public static string INGREDIENT_SECTION {
            get {
                return ResourceManager.GetString("INGREDIENT_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requires Aging.
        /// </summary>
        public static string IS_AGING_REQUIRED {
            get {
                return ResourceManager.GetString("IS_AGING_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action.
        /// </summary>
        public static string LABEL_ACTION {
            get {
                return ResourceManager.GetString("LABEL_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address:.
        /// </summary>
        public static string LABEL_ADDRESS {
            get {
                return ResourceManager.GetString("LABEL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available Warehouse Containers:.
        /// </summary>
        public static string LABEL_AVAILABLE_CONTAINERS {
            get {
                return ResourceManager.GetString("LABEL_AVAILABLE_CONTAINERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available warehouse containers (click + to add):.
        /// </summary>
        public static string LABEL_AVAILABLE_CONTAINERS_HINT {
            get {
                return ResourceManager.GetString("LABEL_AVAILABLE_CONTAINERS_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string LABEL_EQUIPMENT_NAME {
            get {
                return ResourceManager.GetString("LABEL_EQUIPMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expiration Date:.
        /// </summary>
        public static string LABEL_EXPIRATION_DATE {
            get {
                return ResourceManager.GetString("LABEL_EXPIRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hum, %:.
        /// </summary>
        public static string LABEL_HUMIDITY_SHORT {
            get {
                return ResourceManager.GetString("LABEL_HUMIDITY_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string LABEL_LANGUAGE {
            get {
                return ResourceManager.GetString("LABEL_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location.
        /// </summary>
        public static string LABEL_PARENT_LOCATION {
            get {
                return ResourceManager.GetString("LABEL_PARENT_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raw Material.
        /// </summary>
        public static string LABEL_RAW_MATERIAL {
            get {
                return ResourceManager.GetString("LABEL_RAW_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balance.
        /// </summary>
        public static string LABEL_REMAINING_STOCK {
            get {
                return ResourceManager.GetString("LABEL_REMAINING_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Supplier:.
        /// </summary>
        public static string LABEL_SELECT_SUPPLIER {
            get {
                return ResourceManager.GetString("LABEL_SELECT_SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected containers for this lot:.
        /// </summary>
        public static string LABEL_SELECTED_CONTAINERS_HINT {
            get {
                return ResourceManager.GetString("LABEL_SELECTED_CONTAINERS_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Storage Containers.
        /// </summary>
        public static string LABEL_STORAGE_CONTAINERS {
            get {
                return ResourceManager.GetString("LABEL_STORAGE_CONTAINERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supplier:.
        /// </summary>
        public static string LABEL_SUPPLIER_FILTER {
            get {
                return ResourceManager.GetString("LABEL_SUPPLIER_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temp, °C:.
        /// </summary>
        public static string LABEL_TEMP_SHORT {
            get {
                return ResourceManager.GetString("LABEL_TEMP_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        public static string LABEL_THEME {
            get {
                return ResourceManager.GetString("LABEL_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string LABEL_TYPE {
            get {
                return ResourceManager.GetString("LABEL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Container Count (opt.):.
        /// </summary>
        public static string LABEL_UNITS_COUNT {
            get {
                return ResourceManager.GetString("LABEL_UNITS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume / Capacity.
        /// </summary>
        public static string LABEL_VOLUME {
            get {
                return ResourceManager.GetString("LABEL_VOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouse:.
        /// </summary>
        public static string LABEL_WAREHOUSE_FILTER {
            get {
                return ResourceManager.GetString("LABEL_WAREHOUSE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string LANG_EN_DISPLAY {
            get {
                return ResourceManager.GetString("LANG_EN_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string LANG_RU_DISPLAY {
            get {
                return ResourceManager.GetString("LANG_RU_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Українська.
        /// </summary>
        public static string LANG_UA_DISPLAY {
            get {
                return ResourceManager.GetString("LANG_UA_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lot Volume / Weight (l/kg):.
        /// </summary>
        public static string LOT_QUANTITY {
            get {
                return ResourceManager.GetString("LOT_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access Keys (Admin).
        /// </summary>
        public static string NAV_ADMIN_KEYS {
            get {
                return ResourceManager.GetString("NAV_ADMIN_KEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event Log.
        /// </summary>
        public static string NAV_AUDIT {
            get {
                return ResourceManager.GetString("NAV_AUDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign In.
        /// </summary>
        public static string NAV_AUTH {
            get {
                return ResourceManager.GetString("NAV_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supply Planning.
        /// </summary>
        public static string NAV_MRP {
            get {
                return ResourceManager.GetString("NAV_MRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchases &amp; Supplies.
        /// </summary>
        public static string NAV_PROCUREMENT {
            get {
                return ResourceManager.GetString("NAV_PROCUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cheese House.
        /// </summary>
        public static string NAV_PRODUCTION {
            get {
                return ResourceManager.GetString("NAV_PRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Profile.
        /// </summary>
        public static string NAV_PROFILE {
            get {
                return ResourceManager.GetString("NAV_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raw &amp; Recipes.
        /// </summary>
        public static string NAV_RECIPES {
            get {
                return ResourceManager.GetString("NAV_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sales &amp; Orders.
        /// </summary>
        public static string NAV_SALES {
            get {
                return ResourceManager.GetString("NAV_SALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stores &amp; Equipment.
        /// </summary>
        public static string NAV_STORAGE {
            get {
                return ResourceManager.GetString("NAV_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batch History.
        /// </summary>
        public static string NAV_TRACEABILITY {
            get {
                return ResourceManager.GetString("NAV_TRACEABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production batch not found.
        /// </summary>
        public static string PRODUCTION_BATCH_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCTION_BATCH_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient raw materials!.
        /// </summary>
        public static string PRODUCTION_INSUFFICIENT_RAW_MATERIAL {
            get {
                return ResourceManager.GetString("PRODUCTION_INSUFFICIENT_RAW_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Material Name:.
        /// </summary>
        public static string RAW_MATERIAL_NAME {
            get {
                return ResourceManager.GetString("RAW_MATERIAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recipe Name:.
        /// </summary>
        public static string RECIPE_NAME {
            get {
                return ResourceManager.GetString("RECIPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient product stock!.
        /// </summary>
        public static string SALES_INSUFFICIENT_PRODUCT_STOCK {
            get {
                return ResourceManager.GetString("SALES_INSUFFICIENT_PRODUCT_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Raw Material:.
        /// </summary>
        public static string SELECT_RAW_MATERIAL {
            get {
                return ResourceManager.GetString("SELECT_RAW_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Unit:.
        /// </summary>
        public static string SELECT_UOM {
            get {
                return ResourceManager.GetString("SELECT_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Warehouse:.
        /// </summary>
        public static string SELECT_WAREHOUSE {
            get {
                return ResourceManager.GetString("SELECT_WAREHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email:.
        /// </summary>
        public static string SUPPLIER_EMAIL {
            get {
                return ResourceManager.GetString("SUPPLIER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company Name / Full Name:.
        /// </summary>
        public static string SUPPLIER_NAME {
            get {
                return ResourceManager.GetString("SUPPLIER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone:.
        /// </summary>
        public static string SUPPLIER_PHONE {
            get {
                return ResourceManager.GetString("SUPPLIER_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid phone number format (7 to 15 digits required).
        /// </summary>
        public static string SUPPLIER_PHONE_NUMBER_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("SUPPLIER.PHONE_NUMBER_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inbound &amp; Stock Balances.
        /// </summary>
        public static string TAB_STOCK_RECEIPT {
            get {
                return ResourceManager.GetString("TAB_STOCK_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raw Material Suppliers.
        /// </summary>
        public static string TAB_SUPPLIERS {
            get {
                return ResourceManager.GetString("TAB_SUPPLIERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write-off &amp; Losses.
        /// </summary>
        public static string TAB_WRITE_OFF {
            get {
                return ResourceManager.GetString("TAB_WRITE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base Output Yield (kg/l):.
        /// </summary>
        public static string TARGET_OUTPUT_QUANTITY {
            get {
                return ResourceManager.GetString("TARGET_OUTPUT_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🌙 Dark.
        /// </summary>
        public static string THEME_DARK_DISPLAY {
            get {
                return ResourceManager.GetString("THEME_DARK_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ☀️ Light.
        /// </summary>
        public static string THEME_LIGHT_DISPLAY {
            get {
                return ResourceManager.GetString("THEME_LIGHT_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string TITLE_ERROR {
            get {
                return ResourceManager.GetString("TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string TITLE_INFO {
            get {
                return ResourceManager.GetString("TITLE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Procurement &amp; Deliveries.
        /// </summary>
        public static string TITLE_PROCUREMENT {
            get {
                return ResourceManager.GetString("TITLE_PROCUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raw Materials &amp; Tech Recipes.
        /// </summary>
        public static string TITLE_RECIPES {
            get {
                return ResourceManager.GetString("TITLE_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouses &amp; Equipment.
        /// </summary>
        public static string TITLE_STORAGE {
            get {
                return ResourceManager.GetString("TITLE_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        public static string TITLE_SUCCESS {
            get {
                return ResourceManager.GetString("TITLE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string TITLE_WARNING {
            get {
                return ResourceManager.GetString("TITLE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production batch completed! Product in stock..
        /// </summary>
        public static string UI_BATCH_COMPLETED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_BATCH_COMPLETED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batch cost calculated.
        /// </summary>
        public static string UI_BATCH_COST_CALCULATED {
            get {
                return ResourceManager.GetString("UI_BATCH_COST_CALCULATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production batch started!.
        /// </summary>
        public static string UI_BATCH_STARTED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_BATCH_STARTED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer created successfully.
        /// </summary>
        public static string UI_CUSTOMER_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_CUSTOMER_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data load error.
        /// </summary>
        public static string UI_DATA_LOAD_ERROR {
            get {
                return ResourceManager.GetString("UI_DATA_LOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data loaded successfully.
        /// </summary>
        public static string UI_DATA_LOADED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_DATA_LOADED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report exported successfully.
        /// </summary>
        public static string UI_EXPORT_SUCCESS {
            get {
                return ResourceManager.GetString("UI_EXPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in all required fields!.
        /// </summary>
        public static string UI_INVALID_INPUT_FIELDS {
            get {
                return ResourceManager.GetString("UI_INVALID_INPUT_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login successful.
        /// </summary>
        public static string UI_LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("UI_LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order shipped successfully!.
        /// </summary>
        public static string UI_ORDER_SHIPPED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_ORDER_SHIPPED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product created successfully.
        /// </summary>
        public static string UI_PRODUCT_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_PRODUCT_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raw material added successfully.
        /// </summary>
        public static string UI_RAW_MATERIAL_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_RAW_MATERIAL_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recipe saved successfully.
        /// </summary>
        public static string UI_RECIPE_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_RECIPE_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User registered successfully.
        /// </summary>
        public static string UI_REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("UI_REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stock lot added successfully.
        /// </summary>
        public static string UI_STOCK_LOT_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_STOCK_LOT_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unit of Measure created successfully.
        /// </summary>
        public static string UI_UOM_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_UOM_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouse created successfully.
        /// </summary>
        public static string UI_WAREHOUSE_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_WAREHOUSE_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unit Price:.
        /// </summary>
        public static string UNIT_PRICE {
            get {
                return ResourceManager.GetString("UNIT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouse Name.
        /// </summary>
        public static string WAREHOUSE_NAME {
            get {
                return ResourceManager.GetString("WAREHOUSE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouses.
        /// </summary>
        public static string WAREHOUSES_HEADER {
            get {
                return ResourceManager.GetString("WAREHOUSES_HEADER", resourceCulture);
            }
        }
    }
}
