//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraftFlow.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CraftFlow.Wpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ACTIVE BATCHES.
        /// </summary>
        public static string ACTIVE_BATCHES {
            get {
                return ResourceManager.GetString("ACTIVE_BATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actual Output Quantity:.
        /// </summary>
        public static string ACTUAL_OUTPUT_QUANTITY {
            get {
                return ResourceManager.GetString("ACTUAL_OUTPUT_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Stock Lot.
        /// </summary>
        public static string ADD_STOCK_LOT {
            get {
                return ResourceManager.GetString("ADD_STOCK_LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batch Number:.
        /// </summary>
        public static string BATCH_NUMBER {
            get {
                return ResourceManager.GetString("BATCH_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string BTN_ADD {
            get {
                return ResourceManager.GetString("BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log Out.
        /// </summary>
        public static string BTN_LOGOUT {
            get {
                return ResourceManager.GetString("BTN_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculate Batch Cost.
        /// </summary>
        public static string CALCULATE_BATCH_COST {
            get {
                return ResourceManager.GetString("CALCULATE_BATCH_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action.
        /// </summary>
        public static string COL_ACTION {
            get {
                return ResourceManager.GetString("COL_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created At (UTC).
        /// </summary>
        public static string COL_CREATED_AT {
            get {
                return ResourceManager.GetString("COL_CREATED_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string COL_DETAILS {
            get {
                return ResourceManager.GetString("COL_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entity Name.
        /// </summary>
        public static string COL_ENTITY_NAME {
            get {
                return ResourceManager.GetString("COL_ENTITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complete Production Batch.
        /// </summary>
        public static string COMPLETE_PRODUCTION_BATCH {
            get {
                return ResourceManager.GetString("COMPLETE_PRODUCTION_BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Customer.
        /// </summary>
        public static string CREATE_CUSTOMER {
            get {
                return ResourceManager.GetString("CREATE_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Product.
        /// </summary>
        public static string CREATE_PRODUCT {
            get {
                return ResourceManager.GetString("CREATE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Raw Material.
        /// </summary>
        public static string CREATE_RAW_MATERIAL {
            get {
                return ResourceManager.GetString("CREATE_RAW_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Recipe.
        /// </summary>
        public static string CREATE_RECIPE {
            get {
                return ResourceManager.GetString("CREATE_RECIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create UOM.
        /// </summary>
        public static string CREATE_UOM {
            get {
                return ResourceManager.GetString("CREATE_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Warehouse.
        /// </summary>
        public static string CREATE_WAREHOUSE {
            get {
                return ResourceManager.GetString("CREATE_WAREHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer Name:.
        /// </summary>
        public static string CUSTOMER_NAME {
            get {
                return ResourceManager.GetString("CUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer Phone:.
        /// </summary>
        public static string CUSTOMER_PHONE {
            get {
                return ResourceManager.GetString("CUSTOMER_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CUSTOMERS.
        /// </summary>
        public static string CUSTOMERS {
            get {
                return ResourceManager.GetString("CUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email:.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export CSV.
        /// </summary>
        public static string EXPORT_CSV {
            get {
                return ResourceManager.GetString("EXPORT_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full Name:.
        /// </summary>
        public static string FULL_NAME {
            get {
                return ResourceManager.GetString("FULL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requested resource not found.
        /// </summary>
        public static string GENERAL_NOT_FOUND {
            get {
                return ResourceManager.GetString("GENERAL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Guest (not logged in).
        /// </summary>
        public static string GUEST_USER {
            get {
                return ResourceManager.GetString("GUEST_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Recipe.
        /// </summary>
        public static string HEADER_NEW_RECIPE {
            get {
                return ResourceManager.GetString("HEADER_NEW_RECIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raw Materials &amp; Ingredients.
        /// </summary>
        public static string HEADER_RAW_MATERIALS {
            get {
                return ResourceManager.GetString("HEADER_RAW_MATERIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Technology Recipes.
        /// </summary>
        public static string HEADER_RECIPES {
            get {
                return ResourceManager.GetString("HEADER_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ingredient Quantity:.
        /// </summary>
        public static string INGREDIENT_QUANTITY {
            get {
                return ResourceManager.GetString("INGREDIENT_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INGREDIENT SECTION.
        /// </summary>
        public static string INGREDIENT_SECTION {
            get {
                return ResourceManager.GetString("INGREDIENT_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requires Aging.
        /// </summary>
        public static string IS_AGING_REQUIRED {
            get {
                return ResourceManager.GetString("IS_AGING_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string LABEL_LANGUAGE {
            get {
                return ResourceManager.GetString("LABEL_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        public static string LABEL_THEME {
            get {
                return ResourceManager.GetString("LABEL_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string LANG_EN_DISPLAY {
            get {
                return ResourceManager.GetString("LANG_EN_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string LANG_RU_DISPLAY {
            get {
                return ResourceManager.GetString("LANG_RU_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Українська.
        /// </summary>
        public static string LANG_UA_DISPLAY {
            get {
                return ResourceManager.GetString("LANG_UA_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login &amp; Use Token.
        /// </summary>
        public static string LOGIN_USE_TOKEN {
            get {
                return ResourceManager.GetString("LOGIN_USE_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lot Quantity:.
        /// </summary>
        public static string LOT_QUANTITY {
            get {
                return ResourceManager.GetString("LOT_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access Keys (Admin).
        /// </summary>
        public static string NAV_ADMIN_KEYS {
            get {
                return ResourceManager.GetString("NAV_ADMIN_KEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event Log.
        /// </summary>
        public static string NAV_AUDIT {
            get {
                return ResourceManager.GetString("NAV_AUDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign In.
        /// </summary>
        public static string NAV_AUTH {
            get {
                return ResourceManager.GetString("NAV_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supply Planning.
        /// </summary>
        public static string NAV_MRP {
            get {
                return ResourceManager.GetString("NAV_MRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchases &amp; Supplies.
        /// </summary>
        public static string NAV_PROCUREMENT {
            get {
                return ResourceManager.GetString("NAV_PROCUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cheese House.
        /// </summary>
        public static string NAV_PRODUCTION {
            get {
                return ResourceManager.GetString("NAV_PRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Profile.
        /// </summary>
        public static string NAV_PROFILE {
            get {
                return ResourceManager.GetString("NAV_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raw &amp; Recipes.
        /// </summary>
        public static string NAV_RECIPES {
            get {
                return ResourceManager.GetString("NAV_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sales &amp; Orders.
        /// </summary>
        public static string NAV_SALES {
            get {
                return ResourceManager.GetString("NAV_SALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stores &amp; Equipment.
        /// </summary>
        public static string NAV_STORAGE {
            get {
                return ResourceManager.GetString("NAV_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batch History.
        /// </summary>
        public static string NAV_TRACEABILITY {
            get {
                return ResourceManager.GetString("NAV_TRACEABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Planned Output Quantity:.
        /// </summary>
        public static string PLANNED_OUTPUT_QUANTITY {
            get {
                return ResourceManager.GetString("PLANNED_OUTPUT_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product Name:.
        /// </summary>
        public static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production batch not found.
        /// </summary>
        public static string PRODUCTION_BATCH_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCTION_BATCH_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient raw materials!.
        /// </summary>
        public static string PRODUCTION_INSUFFICIENT_RAW_MATERIAL {
            get {
                return ResourceManager.GetString("PRODUCTION_INSUFFICIENT_RAW_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PRODUCTS / RECIPES.
        /// </summary>
        public static string PRODUCTS_RECIPES {
            get {
                return ResourceManager.GetString("PRODUCTS_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity:.
        /// </summary>
        public static string QUANTITY {
            get {
                return ResourceManager.GetString("QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raw Material Name:.
        /// </summary>
        public static string RAW_MATERIAL_NAME {
            get {
                return ResourceManager.GetString("RAW_MATERIAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recipe Name:.
        /// </summary>
        public static string RECIPE_NAME {
            get {
                return ResourceManager.GetString("RECIPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string REFRESH_LOGS {
            get {
                return ResourceManager.GetString("REFRESH_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        public static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient product stock!.
        /// </summary>
        public static string SALES_INSUFFICIENT_PRODUCT_STOCK {
            get {
                return ResourceManager.GetString("SALES_INSUFFICIENT_PRODUCT_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Active Batch:.
        /// </summary>
        public static string SELECT_ACTIVE_BATCH {
            get {
                return ResourceManager.GetString("SELECT_ACTIVE_BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Customer:.
        /// </summary>
        public static string SELECT_CUSTOMER {
            get {
                return ResourceManager.GetString("SELECT_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Product:.
        /// </summary>
        public static string SELECT_PRODUCT {
            get {
                return ResourceManager.GetString("SELECT_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Raw Material:.
        /// </summary>
        public static string SELECT_RAW_MATERIAL {
            get {
                return ResourceManager.GetString("SELECT_RAW_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Recipe:.
        /// </summary>
        public static string SELECT_RECIPE {
            get {
                return ResourceManager.GetString("SELECT_RECIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select UOM:.
        /// </summary>
        public static string SELECT_UOM {
            get {
                return ResourceManager.GetString("SELECT_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Warehouse:.
        /// </summary>
        public static string SELECT_WAREHOUSE {
            get {
                return ResourceManager.GetString("SELECT_WAREHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ship Order.
        /// </summary>
        public static string SHIP_ORDER {
            get {
                return ResourceManager.GetString("SHIP_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ship Sales Order.
        /// </summary>
        public static string SHIP_SALES_ORDER {
            get {
                return ResourceManager.GetString("SHIP_SALES_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Production Batch.
        /// </summary>
        public static string START_PRODUCTION_BATCH {
            get {
                return ResourceManager.GetString("START_PRODUCTION_BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target Output Quantity:.
        /// </summary>
        public static string TARGET_OUTPUT_QUANTITY {
            get {
                return ResourceManager.GetString("TARGET_OUTPUT_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🌙 Dark.
        /// </summary>
        public static string THEME_DARK_DISPLAY {
            get {
                return ResourceManager.GetString("THEME_DARK_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ☀️ Light.
        /// </summary>
        public static string THEME_LIGHT_DISPLAY {
            get {
                return ResourceManager.GetString("THEME_LIGHT_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raw Materials &amp; Tech Recipes.
        /// </summary>
        public static string TITLE_RECIPES {
            get {
                return ResourceManager.GetString("TITLE_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TOTAL RAW MATERIAL COST:.
        /// </summary>
        public static string TOTAL_RAW_MATERIAL_COST {
            get {
                return ResourceManager.GetString("TOTAL_RAW_MATERIAL_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TOTAL REVENUE.
        /// </summary>
        public static string TOTAL_REVENUE {
            get {
                return ResourceManager.GetString("TOTAL_REVENUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TOTAL SALES REVENUE.
        /// </summary>
        public static string TOTAL_SALES_REVENUE {
            get {
                return ResourceManager.GetString("TOTAL_SALES_REVENUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TOTAL STOCK QTY.
        /// </summary>
        public static string TOTAL_STOCK_QTY {
            get {
                return ResourceManager.GetString("TOTAL_STOCK_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production batch completed! Product in stock..
        /// </summary>
        public static string UI_BATCH_COMPLETED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_BATCH_COMPLETED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batch cost calculated.
        /// </summary>
        public static string UI_BATCH_COST_CALCULATED {
            get {
                return ResourceManager.GetString("UI_BATCH_COST_CALCULATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production batch started!.
        /// </summary>
        public static string UI_BATCH_STARTED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_BATCH_STARTED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer created successfully.
        /// </summary>
        public static string UI_CUSTOMER_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_CUSTOMER_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data load error.
        /// </summary>
        public static string UI_DATA_LOAD_ERROR {
            get {
                return ResourceManager.GetString("UI_DATA_LOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data loaded successfully.
        /// </summary>
        public static string UI_DATA_LOADED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_DATA_LOADED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report exported successfully.
        /// </summary>
        public static string UI_EXPORT_SUCCESS {
            get {
                return ResourceManager.GetString("UI_EXPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in all required fields!.
        /// </summary>
        public static string UI_INVALID_INPUT_FIELDS {
            get {
                return ResourceManager.GetString("UI_INVALID_INPUT_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login successful.
        /// </summary>
        public static string UI_LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("UI_LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order shipped successfully!.
        /// </summary>
        public static string UI_ORDER_SHIPPED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_ORDER_SHIPPED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product created successfully.
        /// </summary>
        public static string UI_PRODUCT_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_PRODUCT_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raw material added successfully.
        /// </summary>
        public static string UI_RAW_MATERIAL_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_RAW_MATERIAL_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recipe saved successfully.
        /// </summary>
        public static string UI_RECIPE_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_RECIPE_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User registered successfully.
        /// </summary>
        public static string UI_REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("UI_REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stock lot added successfully.
        /// </summary>
        public static string UI_STOCK_LOT_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_STOCK_LOT_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unit of Measure created successfully.
        /// </summary>
        public static string UI_UOM_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_UOM_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouse created successfully.
        /// </summary>
        public static string UI_WAREHOUSE_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("UI_WAREHOUSE_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UNIT COST (PER KG/UNIT):.
        /// </summary>
        public static string UNIT_COST_PER_UNIT {
            get {
                return ResourceManager.GetString("UNIT_COST_PER_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unit Price:.
        /// </summary>
        public static string UNIT_PRICE {
            get {
                return ResourceManager.GetString("UNIT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UOM Code:.
        /// </summary>
        public static string UOM_CODE {
            get {
                return ResourceManager.GetString("UOM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UOM Name:.
        /// </summary>
        public static string UOM_NAME {
            get {
                return ResourceManager.GetString("UOM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouse Address:.
        /// </summary>
        public static string WAREHOUSE_ADDRESS {
            get {
                return ResourceManager.GetString("WAREHOUSE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouse Name:.
        /// </summary>
        public static string WAREHOUSE_NAME {
            get {
                return ResourceManager.GetString("WAREHOUSE_NAME", resourceCulture);
            }
        }
    }
}
